---
abstract: "Indent printing 'CSS::Struct' structure to CSS code."
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CSS-Struct-Output-Indent
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  CSS::Struct::Output: 0.01
  Indent: 0.01
  Readonly: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=CSS-Struct-Output-Indent
  homepage: https://github.com/michal-josef-spacek/CSS-Struct-Output-Indent
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/CSS-Struct-Output-Indent
version: '0.03'
