---
abstract: "Indent printing 'CSS::Structure' structure to CSS code."
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.01
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CSS-Structure-Output-Indent
no_index:
  directory:
    - inc
    - t
requires:
  CSS::Structure::Output::Core: 0.01
  Indent: 0.01
  Readonly: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=CSS-Structure-Output-Indent
  homepage: https://github.com/tupinek/CSS-Structure-Output-Indent
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/CSS-Structure-Output-Indent
version: 0.01
